### ISSUE TITLE
All but first photo is lost from messages containing multiple photos

### ISSUE THREAD

**Issue by goldan** [abul4fia/teletolo#2]
I have a message in telegram that contains 5 photos (and only those, no text). In logseq, I get 5 blocks referencing the same file, that contains the first photo from Telegram. The other 4 photos disappear.

**Comment by abul4fia** [comment]
Thanks for the report. The problem was that the filename for the downloaded images was based exclusively on the timestamp of the messages in the Telegram servers. So when several images are uploaded at once in Telegram, all will have the same timestamp and my script stored all of them under the same filename, causing overwritting.

Now the filenames include a suffix _0, _1, _2, to differentiate among files with the same timestamp in the server, so that overwritting does not happen.

**Comment by goldan** [comment]
Great, thanks for the quick fix!
